# Generated by Django 4.2.6 on 2023-10-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_published'),
        ),
    ]
